import { TourDefinition } from '@shared/components/tour/tour.models';

const MOBILE_SIDEBAR_TARGET = '#sidebar';

export const NOAH_STUDIO_TOUR: TourDefinition = {
  id: 'noah-studio',
  title: 'NOAH Studio',
  startEvent: 'noah-studio-playground-reset',
  welcome: {
    title: 'Welcome to',
    accentTitle: 'NOAH Studio',
    text: 'Explore hazard maps, weather data, and disaster risk information for the Philippines.',
    prompt:
      'Take a quick tour to get started, or explore on your own. If you skip the tour, you can return to it anytime using the Help button on the Map.',
    brandLabel: 'STUDIO',
    logoUrl: 'assets/icons/logo-noah.svg',
    logoAlt: 'Project NOAH',
    imageUrl: 'assets/images/tour/noah-studio-welcome-image.svg',
    imageAlt: 'NOAH Studio map preview',
  },
  sections: [
    {
      id: 'welcome',
      label: 'Welcome',
      steps: [
        {
          id: 'welcome',
          title: 'Welcome!',
          text: 'This is the beginning of the NOAH Studio tutorial. This walkthrough will guide you through the main tools, navigation, and features you can use to explore hazard maps, weather data, and disaster risk information across the Philippines.',
        },
      ],
    },
    {
      id: 'map-navigation',
      label: 'Map Navigation',
      steps: [
        {
          id: 'pan-around-map',
          title: 'Pan Around the Map',
          text: 'Left-click and drag anywhere on the map to move around and explore different locations.\n\n**For mobile:** Touch and drag anywhere on the map with one finger.',
          target: '[data-tour-id="map-canvas"]',
          dimTargets: ['#sidebar'],
          placement: 'bottom-right',
        },
        {
          id: 'rotate-and-tilt-view',
          title: 'Rotate and Tilt View',
          text: 'Right-click and drag on the map to rotate your view or tilt the map for a different perspective.\n\n**For mobile:** Use two fingers to rotate the map. Drag two fingers up or down together to tilt the view.',
          target: '[data-tour-id="map-canvas"]',
          dimTargets: ['#sidebar'],
          placement: 'bottom-right',
        },
        {
          id: 'search-bar',
          title: 'Search Bar',
          text: 'Use the Search Location bar to jump to any city, municipality, or barangay in the Philippines. Just type a name, choose from the searched locations, and the map will travel there instantly.',
          target: '[data-tour-id="location-search"]',
          spotlightTargets: ['[data-tour-id="location-search-options"]'],
          advanceOnEvent: 'noah-tour-location-selected',
          nextEvent: 'noah-tour-location-search-skipped',
          placement: 'right',
        },
        {
          id: 'explore-location',
          title: 'Explore a Location',
          text: 'After searching for a location, move the pin to any point on the map to view available hazard, weather, and disaster risk data for that place.',
          target: '[data-tour-id="map-canvas"]',
          dimTargets: ['#sidebar'],
          nextEvent: 'noah-tour-map-camera-reset',
          placement: 'bottom-right',
        },
      ],
    },
    {
      id: 'map-controls',
      label: 'Map Controls',
      steps: [
        {
          id: 'map-controls-1',
          title: 'Map Controls',
          text: 'Use these map controls to adjust how you view and interact with the map. These tools let you change map views, access the tour, and use extra map information.',
          target: '[data-tour-id="mapbox-map-controls"]',
          spotlightTargets: [
            '[data-tour-id="map-view"]',
            '[data-tour-id="map-view-options"]',
            '[data-tour-id="map-measurement-output"]',
          ],
          interactionTargets: ['[data-tour-id="map-canvas"]'],
          panelAvoidTargets: [
            '[data-tour-id="map-view-options"]',
            '[data-tour-id="map-measurement-output"]',
          ],
          mobilePanelTarget: MOBILE_SIDEBAR_TARGET,
          dimTargets: ['#sidebar'],
          placement: 'left',
        },
        {
          id: 'map-controls-2',
          title: 'Zoom Controls',
          text: 'Use the plus and minus buttons to zoom in for more detail or zoom out for a wider view.',
          target: '[data-tour-id="mapbox-zoom-in"]',
          spotlightTargets: [
            '[data-tour-id="mapbox-zoom-out"]',
            '[data-tour-id="map-canvas"]',
          ],
          mobilePanelTarget: MOBILE_SIDEBAR_TARGET,
          dimTargets: [
            '#sidebar',
            '[data-tour-id="mapbox-geolocate"]',
            '[data-tour-id="mapbox-compass"]',
            '[data-tour-id="map-view"]',
            '[data-tour-id="mapbox-draw-line"]',
            '[data-tour-id="mapbox-draw-polygon"]',
            '[data-tour-id="mapbox-draw-trash"]',
            '[data-tour-id="map-scale-control"]',
            '[data-tour-id="tour-help-info"]',
          ],
          placement: 'left',
        },
        {
          id: 'map-controls-3',
          title: 'Reset Map Direction',
          text: 'If the map has been rotated or tilted, you can use this control to return the view to its default direction.',
          target: '[data-tour-id="mapbox-compass"]',
          spotlightTargets: ['[data-tour-id="map-canvas"]'],
          mobilePanelTarget: MOBILE_SIDEBAR_TARGET,
          dimTargets: [
            '#sidebar',
            '[data-tour-id="map-view"]',
            '[data-tour-id="mapbox-geolocate"]',
            '[data-tour-id="mapbox-zoom-in"]',
            '[data-tour-id="mapbox-zoom-out"]',
            '[data-tour-id="mapbox-draw-line"]',
            '[data-tour-id="mapbox-draw-polygon"]',
            '[data-tour-id="mapbox-draw-trash"]',
            '[data-tour-id="map-scale-control"]',
            '[data-tour-id="tour-help-info"]',
          ],
          placement: 'left',
        },

        {
          id: 'map-controls-4',
          title: 'Current Location',
          text: 'This map control button moves the map to your current location, making it easier to check nearby hazards, weather data, and disaster risk information.',
          target: '[data-tour-id="mapbox-geolocate"]',
          spotlightTargets: ['[data-tour-id="map-canvas"]'],
          mobilePanelTarget: MOBILE_SIDEBAR_TARGET,
          dimTargets: [
            '#sidebar',
            '[data-tour-id="map-view"]',
            '[data-tour-id="mapbox-zoom-in"]',
            '[data-tour-id="mapbox-zoom-out"]',
            '[data-tour-id="mapbox-draw-line"]',
            '[data-tour-id="mapbox-draw-polygon"]',
            '[data-tour-id="mapbox-draw-trash"]',
            '[data-tour-id="mapbox-compass"]',
            '[data-tour-id="map-scale-control"]',
            '[data-tour-id="tour-help-info"]',
          ],
          placement: 'left',
        },

        {
          id: 'map-controls-5',
          title: 'Measure Distance and Area',
          text: 'Use these tools to measure distances and areas on the map. The line tool measures distance, the rectangle tool measures area, and the delete button removes any highlighted measurements you have added. In the drawing phase, double click on the same spot to end the drawing.',
          target: '[data-tour-id="mapbox-draw-line"]',
          spotlightTargets: [
            '[data-tour-id="mapbox-draw-polygon"]',
            '[data-tour-id="mapbox-draw-trash"]',
            '[data-tour-id="map-canvas"]',
          ],
          panelAvoidTargets: ['[data-tour-id="map-measurement-output"]'],
          mobilePanelTarget: MOBILE_SIDEBAR_TARGET,
          dimTargets: [
            '#sidebar',
            '[data-tour-id="mapbox-geolocate"]',
            '[data-tour-id="mapbox-zoom-in"]',
            '[data-tour-id="map-view"]',
            '[data-tour-id="mapbox-zoom-out"]',
            '[data-tour-id="mapbox-compass"]',
            '[data-tour-id="map-scale-control"]',
            '[data-tour-id="tour-help-info"]',
          ],
          placement: 'left',
        },

        {
          id: 'map-controls-6',
          title: 'Change Map View',
          text: 'Switch between different map views to better understand the area you are looking at. The current map views available are satellite and terrain view.',
          target: '[data-tour-id="map-view"]',
          spotlightTargets: ['[data-tour-id="map-canvas"]'],
          panelAvoidTargets: ['[data-tour-id="map-view-options"]'],
          mobilePanelTarget: MOBILE_SIDEBAR_TARGET,
          dimTargets: [
            '#sidebar',
            '[data-tour-id="mapbox-geolocate"]',
            '[data-tour-id="mapbox-zoom-in"]',
            '[data-tour-id="mapbox-zoom-out"]',
            '[data-tour-id="mapbox-draw-line"]',
            '[data-tour-id="mapbox-draw-polygon"]',
            '[data-tour-id="mapbox-draw-trash"]',
            '[data-tour-id="mapbox-compass"]',
            '[data-tour-id="map-scale-control"]',
            '[data-tour-id="tour-help-info"]',
          ],
          nextEvent: 'noah-tour-layer-panel-reset',
          placement: 'left',
        },
      ],
    },
    {
      id: 'layer-panel',
      label: 'Layer Panel',
      steps: [
        {
          id: 'layer-panel',
          title: 'Layer Panel',
          text: 'Use the layer panel to explore hazard maps, weather updates, impact forecasts, critical facilities, and other location-based information available in NOAH Studio.',
          target: '[data-tour-id="sidebar-scroll"]',
          placement: 'right',
        },
        {
          id: '3d-terrain',
          title: '3D Terrain',
          text: 'Turn on 3D Terrain to view the map with elevation and landform details. This helps you better understand mountains, slopes, valleys, and other terrain features.\n\nExpand the dropdown to change the **exaggeration** which is how strongly the terrain height appears on the map.',
          target: '[data-tour-id="3d-terrain-header"]',
          spotlightTargets: ['[data-tour-id="3d-terrain"]'],
          placement: 'right',
        },
        {
          id: 'flood-hazard',
          title: 'Flood Hazard',
          text: "The Flood Hazard layer shows areas that may be affected by flooding. Use this to identify places with possible flood exposure during heavy rainfall or extreme weather events.\n\nExpand the dropdown to choose the **return period** you want to view, adjust the layer's **opacity**, and select the **color** used to render it on the map.",
          target: '[data-tour-id="flood-hazard-header"]',
          spotlightTargets: ['[data-tour-id="flood-hazard"]'],
          placement: 'right',
        },
        {
          id: 'weather-updates',
          title: 'Weather Updates',
          text: 'Weather Updates gives you near-real-time data from stations and satellites nationwide.\n\nExpand it to access five sub-layers — **Weather Satellite Image** for cloud and rain coverage, **Typhoon Track** to monitor active storm paths, **Temperature** for current heat readings across the country, **Lightning Data** to track lightning activity, and **Wind** to visualize wind flow patterns across the country.',
          target: '[data-tour-id="weather-updates-header"]',
          spotlightTargets: ['[data-tour-id="weather-updates"]'],
          placement: 'right',
        },
        {
          id: 'flood-impact-forecast',
          title: 'Flood Impact Forecast',
          text: 'Flood Impact Forecast is a beta feature that combines a 24-hour rain forecast with flood-prone population data to estimate potential exposure at the barangay level.\n\nExpand the dropdown to turn on the **Rain Forecast** and **Flood Prone Population** layers, adjust their **opacity**, then select **Calculate Flood Exposure** to view the results.',
          target: '[data-tour-id="flood-impact-forecast-header"]',
          spotlightTargets: ['[data-tour-id="flood-impact-forecast"]'],
          placement: 'right',
        },
        {
          id: 'landslide-hazard',
          title: 'Landslide Hazard',
          text: "Landslide Hazard shows areas susceptible to landslides, debris flows, and alluvial-fan processes. This is especially useful for communities in mountainous areas during periods of heavy rain.\n\nExpand the dropdown to choose **Landslides** or **Debris Flow and Alluvial Fan**, adjust the layer's **opacity**, and select the **color** used to render it on the map.",
          target: '[data-tour-id="landslide-hazard-header"]',
          spotlightTargets: ['[data-tour-id="landslide-hazard"]'],
          placement: 'right',
        },
        {
          id: 'storm-surge-hazard',
          title: 'Storm Surge Hazard',
          text: "Storm Surge Hazard maps coastal areas that could be inundated by seawater pushed inland during a typhoon. Use it to understand which coastal communities may be exposed at different surge heights.\n\nExpand the dropdown to choose **Storm Surge Advisory 1–4**, adjust the layer's **opacity**, and select the **color** used to render it on the map.",
          target: '[data-tour-id="storm-surge-hazard-header"]',
          spotlightTargets: ['[data-tour-id="storm-surge-hazard"]'],
          placement: 'right',
        },
        {
          id: 'volcanoes',
          title: 'Volcanoes',
          text: 'The Volcanoes layer plots volcano locations and groups them by activity classification: active, potentially active, or inactive.\n\nExpand the dropdown to choose one or more **activity classifications**, adjust marker **opacity**, and review the **legend** for each classification.',
          target: '[data-tour-id="volcanoes-header"]',
          spotlightTargets: ['[data-tour-id="volcanoes"]'],
          placement: 'right',
        },
        {
          id: 'critical-facilities',
          title: 'Critical Facilities',
          text: 'Critical Facilities plots hospitals, fire stations, police stations, and schools on the map. These locations can support planning and response before, during, and after a disaster.\n\nExpand the dropdown to choose which **facility types** to display, adjust their marker **opacity**, and use the **legend** to identify them on the map.',
          target: '[data-tour-id="critical-facilities-header"]',
          spotlightTargets: ['[data-tour-id="critical-facilities"]'],
          placement: 'right',
        },
        {
          id: 'internet-of-things',
          title: 'Internet of Things',
          text: 'IoT provides available flood- and rain-sensor readings for Quezon City, together with local administrative boundaries and critical facilities. Sensor datasets are still being calibrated and validated.\n\nExpand the dropdown to choose **Flood** or **Rain** sensors, display municipal or barangay **boundaries** and QC **critical facilities**, then select **View Data Summary** for more details.',
          target: '[data-tour-id="internet-of-things-header"]',
          spotlightTargets: ['[data-tour-id="internet-of-things"]'],
          placement: 'right',
        },
      ],
    },
    {
      id: 'end',
      label: 'End',
      steps: [
        {
          id: 'end',
          title: "You're Ready to Explore",
          text: 'You’ve completed the NOAH Studio tutorial. You can now explore hazard maps, weather updates, risk information, and map tools on your own. Use the layer panel and map controls anytime to adjust what you see and inspect areas across the Philippines.',
          placement: 'center',
        },
      ],
    },
  ],
};
