import { TourDefinition } from '@shared/components/tour/tour.models';

export const NOAH_STUDIO_TOUR: TourDefinition = {
  id: 'noah-studio',
  title: 'NOAH Studio',
  startEvent: 'noah-studio-playground-reset',
  welcome: {
    title: 'Welcome to',
    accentTitle: 'NOAH Studio',
    text: 'Explore hazard maps, weather data, and disaster risk information for the Philippines.',
    prompt: 'Take a quick tour to get started, or explore on your own.',
    brandLabel: 'STUDIO',
    logoUrl: 'assets/icons/logo-noah.svg',
    logoAlt: 'Project NOAH',
    imageUrl: 'assets/images/tour/noah-studio-welcome-image.svg',
    imageAlt: 'NOAH Studio map preview',
  },
  sections: [
    {
      id: 'welcome',
      label: 'Welcome',
      steps: [
        {
          id: 'welcome',
          title: 'Welcome!',
          text: 'This is the beginning of the NOAH Studio tutorial. This walkthrough will guide you through the main tools, navigation, and features you can use to explore hazard maps, weather data, and disaster risk information across the Philippines.',
        },
      ],
    },
    {
      id: 'map-navigation',
      label: 'Map Navigation',
      steps: [
        {
          id: 'pan-around-map',
          title: 'Pan Around the Map',
          text: 'Left-click and drag anywhere on the map to move around and explore different locations.',
          target: '[data-tour-id="map-canvas"]',
          dimTargets: ['#sidebar'],
          placement: 'bottom-right',
        },
        {
          id: 'rotate-and-tilt-view',
          title: 'Rotate and Tilt View',
          text: 'Right-click and drag on the map to rotate your view or tilt the map for a different perspective.',
          target: '[data-tour-id="map-canvas"]',
          dimTargets: ['#sidebar'],
          placement: 'bottom-right',
        },
        {
          id: 'search-bar',
          title: 'Search Bar',
          text: 'Use the Search Location bar to jump to any city, municipality, or barangay in the Philippines. Just type a name, choose from the searched locations, and the map will travel there instantly.',
          target: '[data-tour-id="location-search"]',
          spotlightTargets: ['[data-tour-id="location-search-options"]'],
          advanceOnEvent: 'noah-tour-location-selected',
          nextEvent: 'noah-tour-location-search-skipped',
          placement: 'right',
        },
        {
          id: 'explore-location',
          title: 'Explore a Location',
          text: 'After searching for a location, move the pin to any point on the map to view available hazard, weather, and disaster risk data for that place.',
          target: '[data-tour-id="map-canvas"]',
          dimTargets: ['#sidebar'],
          nextEvent: 'noah-tour-map-camera-reset',
          placement: 'bottom-right',
        },
      ],
    },
    {
      id: 'map-controls',
      label: 'Map Controls',
      steps: [
        {
          id: 'map-controls-1',
          title: 'Map Controls',
          text: 'Use these map controls to adjust how you view and interact with the map. These tools let you change map views, access the tour, and use extra map information.',
          target: '[data-tour-id="mapbox-map-controls"]',
          spotlightTargets: ['[data-tour-id="map-view"]'],
          interactionTargets: ['[data-tour-id="map-canvas"]'],
          dimTargets: ['#sidebar'],
          placement: 'left',
        },
        {
          id: 'map-controls-2',
          title: 'Zoom Controls',
          text: 'Use the plus and minus buttons to zoom in for more detail or zoom out for a wider view.',
          target: '[data-tour-id="mapbox-zoom-in"]',
          spotlightTargets: [
            '[data-tour-id="mapbox-zoom-out"]',
            '[data-tour-id="map-canvas"]',
          ],
          dimTargets: [
            '#sidebar',
            '[data-tour-id="mapbox-geolocate"]',
            '[data-tour-id="mapbox-compass"]',
            '[data-tour-id="map-view"]',
            '[data-tour-id="mapbox-draw-line"]',
            '[data-tour-id="mapbox-draw-polygon"]',
            '[data-tour-id="mapbox-draw-trash"]',
            '[data-tour-id="map-scale-control"]',
            '[data-tour-id="tour-help-info"]',
          ],
          placement: 'left',
        },
        {
          id: 'map-controls-3',
          title: 'Reset Map Direction',
          text: 'If the map has been rotated or tilted, you can use this control to return the view to its default direction.',
          target: '[data-tour-id="mapbox-compass"]',
          spotlightTargets: ['[data-tour-id="map-canvas"]'],
          dimTargets: [
            '#sidebar',
            '[data-tour-id="map-view"]',
            '[data-tour-id="mapbox-geolocate"]',
            '[data-tour-id="mapbox-zoom-in"]',
            '[data-tour-id="mapbox-zoom-out"]',
            '[data-tour-id="mapbox-draw-line"]',
            '[data-tour-id="mapbox-draw-polygon"]',
            '[data-tour-id="mapbox-draw-trash"]',
            '[data-tour-id="map-scale-control"]',
            '[data-tour-id="tour-help-info"]',
          ],
          placement: 'left',
        },

        {
          id: 'map-controls-4',
          title: 'Current Location',
          text: 'This map control button moves the map to your current location, making it easier to check nearby hazards, weather data, and disaster risk information.',
          target: '[data-tour-id="mapbox-geolocate"]',
          spotlightTargets: ['[data-tour-id="map-canvas"]'],
          dimTargets: [
            '#sidebar',
            '[data-tour-id="map-view"]',
            '[data-tour-id="mapbox-zoom-in"]',
            '[data-tour-id="mapbox-zoom-out"]',
            '[data-tour-id="mapbox-draw-line"]',
            '[data-tour-id="mapbox-draw-polygon"]',
            '[data-tour-id="mapbox-draw-trash"]',
            '[data-tour-id="mapbox-compass"]',
            '[data-tour-id="map-scale-control"]',
            '[data-tour-id="tour-help-info"]',
          ],
          placement: 'left',
        },

        {
          id: 'map-controls-5',
          title: 'Measure Distance and Area',
          text: 'Use these tools to measure distances and areas on the map. The line tool measures distance, the rectangle tool measures area, and the delete button removes any highlighted measurements you have added. In the drawing phase, double click on the same spot to end the drawing.',
          target: '[data-tour-id="map-view"]',
          dimTargets: [
            '#sidebar',
            '[data-tour-id="mapbox-geolocate"]',
            '[data-tour-id="mapbox-zoom-in"]',
            '[data-tour-id="mapbox-zoom-out"]',
            '[data-tour-id="mapbox-draw-line"]',
            '[data-tour-id="mapbox-draw-polygon"]',
            '[data-tour-id="mapbox-draw-trash"]',
            '[data-tour-id="mapbox-compass"]',
            '[data-tour-id="map-scale-control"]',
            '[data-tour-id="tour-help-info"]',
          ],
          placement: 'left',
        },

        {
          id: 'map-controls-6',
          title: 'Change Map View',
          text: 'Switch between different map views to better understand the area you are looking at. The current map views available are satellite and terrain view.',
          target: '[data-tour-id="mapbox-draw-line"]',
          spotlightTargets: [
            '[data-tour-id="mapbox-draw-polygon"]',
            '[data-tour-id="mapbox-draw-trash"]',
          ],
          dimTargets: [
            '#sidebar',
            '[data-tour-id="map-view"]',
            '[data-tour-id="mapbox-geolocate"]',
            '[data-tour-id="mapbox-zoom-in"]',
            '[data-tour-id="mapbox-zoom-out"]',
            '[data-tour-id="mapbox-draw-line"]',
            '[data-tour-id="mapbox-draw-polygon"]',
            '[data-tour-id="mapbox-draw-trash"]',
            '[data-tour-id="mapbox-compass"]',
            '[data-tour-id="map-scale-control"]',
            '[data-tour-id="tour-help-info"]',
          ],
          placement: 'left',
        },
      ],
    },
    {
      id: 'layer-panel',
      label: 'Layer Panel',
      steps: [
        {
          id: 'layer-panel',
          title: 'Layer Panel',
          text: 'Use the layer panel to explore hazard maps, weather updates, impact forecasts, critical facilities, and other location-based information available in NOAH Studio.',
          target: '[data-tour-id="sidebar-scroll"]',
          placement: 'right',
        },
        {
          id: '3d-terrain',
          title: '3D Terrain',
          text: 'Turn on 3D Terrain to view the map with elevation and landform details. This helps you better understand mountains, slopes, valleys, and other terrain features. Expand the dropdown to change the exaggeration which is how strongly the terrain height appears on the map.',
          target: '[data-tour-id="3d-terrain-header"]',
          spotlightTargets: ['[data-tour-id="3d-terrain"]'],
          placement: 'right',
        },
        {
          id: 'flood-hazard',
          title: 'Flood Hazard',
          text: 'The Flood Hazard layer shows areas that may be affected by flooding. Use this to identify places with possible flood exposure during heavy rainfall or extreme weather events.',
          target: '[data-tour-id="flood-hazard-header"]',
          spotlightTargets: ['[data-tour-id="flood-hazard"]'],
          placement: 'right',
        },
        {
          id: 'weather-updates',
          title: 'Weather Updates',
          text: 'Weather Updates gives you near-real-time data from stations and satellites nationwide. Expand it to access three sub-layers — Weather Satellite Image for cloud and rain coverage, Typhoon Track to monitor active storm paths, and Temperature for current heat readings across the country.',
          target: '[data-tour-id="weather-updates-header"]',
          spotlightTargets: ['[data-tour-id="weather-updates"]'],
          placement: 'right',
        },
        {
          id: 'flood-impact-forecast',
          title: 'Flood Impact Forecast',
          text: 'A beta feature that combines a 24-hour rain forecast with flood-prone population data. Hit Calculate Flood Exposure to see a barangay-level breakdown of how many people are at risk in a flood event.',
          target: '[data-tour-id="flood-impact-forecast-header"]',
          spotlightTargets: ['[data-tour-id="flood-impact-forecast"]'],
          placement: 'right',
        },
        {
          id: 'landslide-hazard',
          title: 'Landslide Hazard',
          text: 'Landslide Hazard shows areas at risk of slope failures and debris flows — especially critical for communities in mountainous provinces during typhoon season.',
          target: '[data-tour-id="landslide-hazard-header"]',
          spotlightTargets: ['[data-tour-id="landslide-hazard"]'],
          placement: 'right',
        },
        {
          id: 'storm-surge-hazard',
          title: 'Storm Surge Hazard',
          text: 'Storm Surge Hazard maps coastal areas that could be inundated by seawater pushed inland by typhoon winds. This is one of the most dangerous hazards in the Philippines.',
          target: '[data-tour-id="storm-surge-hazard-header"]',
          spotlightTargets: ['[data-tour-id="storm-surge-hazard"]'],
          placement: 'right',
        },
        {
          id: 'volcanoes',
          title: 'Volcanoes',
          text: 'The Volcanoes layer shows active volcanoes along with their permanent and extended danger zones — covering Taal, Mayon, Pinatubo, and more.',
          target: '[data-tour-id="volcanoes-header"]',
          spotlightTargets: ['[data-tour-id="volcanoes"]'],
          placement: 'right',
        },
        {
          id: 'critical-facilities',
          title: 'Critical Facilities',
          text: 'Critical Facilities plots hospitals, fire stations, police stations, and schools on the map. These are important places you may need during and after a disaster.',
          target: '[data-tour-id="critical-facilities-header"]',
          spotlightTargets: ['[data-tour-id="critical-facilities"]'],
          placement: 'right',
        },
        {
          id: 'internet-of-things',
          title: 'Internet of Things',
          text: "IoT shows live readings from NOAH's network of automated rain gauges and water level sensors deployed around the country. Real ground data, in real time.",
          target: '[data-tour-id="internet-of-things-header"]',
          spotlightTargets: ['[data-tour-id="internet-of-things"]'],
          placement: 'right',
        },
      ],
    },
    {
      id: 'end',
      label: 'End',
      steps: [
        {
          id: 'end',
          title: "You're Ready to Explore",
          text: 'You’ve completed the NOAH Studio tutorial. You can now explore hazard maps, weather updates, risk information, and map tools on your own. Use the layer panel and map controls anytime to adjust what you see and inspect areas across the Philippines.',
          placement: 'center',
        },
      ],
    },
  ],
};
