# Generated by Django 4.2.30 on 2026-05-19 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SummaryAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('forecast_timestamp', models.CharField(blank=True, max_length=100)),
                ('model_run', models.CharField(blank=True, max_length=20)),
                ('input_json', models.JSONField()),
                ('output_json', models.JSONField()),
                ('ollama_model', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(choices=[('llm', 'LLM'), ('fallback', 'Fallback')], default='fallback', max_length=20)),
                ('validation_passed', models.BooleanField(default=True)),
                ('validation_failure_reason', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
