# Generated by Django 4.2.30 on 2026-05-22 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ibff_summarizer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('event_name', models.CharField(max_length=100)),
                ('event_date', models.DateField()),
                ('sheet_gid', models.IntegerField(unique=True)),
                ('total_municipalities', models.IntegerField(default=0)),
                ('confirmed_municipalities', models.IntegerField(default=0)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='PastEventSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_output', models.JSONField()),
                ('source', models.CharField(choices=[('llm', 'LLM'), ('fallback', 'Fallback')], default='fallback', max_length=20)),
                ('validation_passed', models.BooleanField(default=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='ibff_summarizer.pastevent')),
            ],
        ),
        migrations.CreateModel(
            name='PastEventMunicipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=200)),
                ('municipality', models.CharField(max_length=200)),
                ('has_flooding_report', models.BooleanField(default=False)),
                ('reference_url', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipalities', to='ibff_summarizer.pastevent')),
            ],
            options={
                'ordering': ['province', 'municipality'],
            },
        ),
    ]
