import { TourDefinition } from '@shared/components/tour/tour.models';

const MOBILE_SIDEBAR_TARGET = '#sidebar';

export const WEATHER_UPDATES_TOUR: TourDefinition = {
  id: 'weather-updates',
  title: 'Weather Updates',
  startEvent: 'weather-updates-reset',
  welcome: {
    title: 'Welcome to',
    accentTitle: 'Weather\u00a0Updates',
    text: 'Monitor current weather conditions across the Philippines.',
    prompt:
      'Take a quick tour to get started, or skip and explore on your own.  If you skip the tour, you can return to it anytime using the Help button on the Map.',
    brandLabel: 'WEATHER UPDATES',
    logoUrl: 'assets/icons/logo-noah.svg',
    logoAlt: 'Project NOAH',
    imageUrl: 'assets/images/tour/weather-welcome-image.svg',
    imageAlt: 'Weather Updates map preview',
  },
  sections: [
    {
      id: 'welcome',
      label: 'Welcome',
      steps: [
        {
          id: 'welcome',
          title: 'Welcome!',
          text: 'This is the beginning of the Weather Updates tutorial. This walkthrough will guide you through navigating the map, viewing weather forecasts, and understanding the weather information shown for your area.',
          placement: 'center',
        },
      ],
    },
    {
      id: 'map-navigation',
      label: 'Map Navigation',
      steps: [
        {
          id: 'pan-around-map',
          title: 'Pan Around the Map',
          text: 'Left-click and drag anywhere on the map to move around and explore different locations.\n\n**For mobile:** Touch and drag anywhere on the map with one finger.',
          target: '[data-tour-id="map-canvas"]',
          dimTargets: ['#sidebar'],
          placement: 'bottom-right',
        },
        {
          id: 'rotate-and-tilt-view',
          title: 'Rotate and Tilt View',
          text: 'Right-click and drag on the map to rotate your view or tilt the map for a different perspective.\n\n**For mobile:** Use two fingers to rotate the map. Drag two fingers up or down together to tilt the view.',
          target: '[data-tour-id="map-canvas"]',
          dimTargets: ['#sidebar'],
          placement: 'bottom-right',
        },
        {
          id: 'search-bar',
          title: 'Search Bar',
          text: 'Use the Search Location bar to jump to any city, municipality, or barangay in the Philippines. Just type a name, choose from the searched locations, and the map will travel there instantly.',
          target: '[data-tour-id="location-search"]',
          spotlightTargets: ['[data-tour-id="location-search-options"]'],
          advanceOnEvent: 'noah-tour-location-selected',
          nextEvent: 'noah-tour-location-search-skipped',
          placement: 'left',
        },
        {
          id: 'explore-location',
          title: 'Explore a Location',
          text: 'After searching for a location, move the pin to any point on the map to view available weather information for that place.',
          target: '[data-tour-id="map-canvas"]',
          dimTargets: ['#sidebar'],
          nextEvent: 'noah-tour-map-camera-reset',
          placement: 'bottom-right',
        },
      ],
    },
    {
      id: 'map-controls',
      label: 'Map Controls',
      steps: [
        {
          id: 'map-controls-1',
          title: 'Map Controls',
          text: 'Use these map controls to adjust how you view and interact with the map. These tools let you change map views, access the tour, and use extra map information.',
          target: '[data-tour-id="mapbox-map-controls"]',
          spotlightTargets: ['[data-tour-id="map-view"]'],
          interactionTargets: ['[data-tour-id="map-canvas"]'],
          mobilePanelTarget: MOBILE_SIDEBAR_TARGET,
          dimTargets: ['#sidebar'],
          placement: 'left',
        },
        {
          id: 'map-controls-2',
          title: 'Zoom Controls',
          text: 'Use the plus and minus buttons to zoom in for more detail or zoom out for a wider view.',
          target: '[data-tour-id="mapbox-zoom-in"]',
          spotlightTargets: [
            '[data-tour-id="mapbox-zoom-out"]',
            '[data-tour-id="map-canvas"]',
          ],
          mobilePanelTarget: MOBILE_SIDEBAR_TARGET,
          dimTargets: [
            '#sidebar',
            '[data-tour-id="mapbox-geolocate"]',
            '[data-tour-id="mapbox-compass"]',
            '[data-tour-id="map-view"]',
            '[data-tour-id="map-scale-control"]',
            '[data-tour-id="tour-help-info"]',
          ],
          placement: 'left',
        },
        {
          id: 'map-controls-3',
          title: 'Reset Map Direction',
          text: 'If the map has been rotated or tilted, you can use this control to return the view to its default direction.',
          target: '[data-tour-id="mapbox-compass"]',
          spotlightTargets: ['[data-tour-id="map-canvas"]'],
          mobilePanelTarget: MOBILE_SIDEBAR_TARGET,
          dimTargets: [
            '#sidebar',
            '[data-tour-id="mapbox-geolocate"]',
            '[data-tour-id="mapbox-zoom-in"]',
            '[data-tour-id="mapbox-zoom-out"]',
            '[data-tour-id="map-view"]',
            '[data-tour-id="map-scale-control"]',
            '[data-tour-id="tour-help-info"]',
          ],
          placement: 'left',
        },
        {
          id: 'map-controls-4',
          title: 'Current Location',
          text: 'This map control button moves the map to your current location, making it easier to check nearby hazards, weather data, and disaster risk information.',
          target: '[data-tour-id="mapbox-geolocate"]',
          spotlightTargets: ['[data-tour-id="map-canvas"]'],
          mobilePanelTarget: MOBILE_SIDEBAR_TARGET,
          dimTargets: [
            '#sidebar',
            '[data-tour-id="mapbox-zoom-in"]',
            '[data-tour-id="mapbox-zoom-out"]',
            '[data-tour-id="mapbox-compass"]',
            '[data-tour-id="map-view"]',
            '[data-tour-id="map-scale-control"]',
            '[data-tour-id="tour-help-info"]',
          ],
          placement: 'left',
        },
        {
          id: 'map-controls-5',
          title: 'Change Map View',
          text: 'Switch between different map views to better understand the area you are looking at. The current map views available are satellite and terrain view.',
          target: '[data-tour-id="map-view"]',
          spotlightTargets: ['[data-tour-id="map-canvas"]'],
          panelAvoidTargets: ['[data-tour-id="map-view-options"]'],
          mobilePanelTarget: MOBILE_SIDEBAR_TARGET,
          dimTargets: [
            '#sidebar',
            '[data-tour-id="mapbox-geolocate"]',
            '[data-tour-id="mapbox-zoom-in"]',
            '[data-tour-id="mapbox-zoom-out"]',
            '[data-tour-id="mapbox-compass"]',
            '[data-tour-id="map-scale-control"]',
            '[data-tour-id="tour-help-info"]',
          ],
          nextEvent: 'weather-updates-rainfall-panel-reset',
          placement: 'left',
        },
      ],
    },
    {
      id: 'rainfall-panel',
      label: 'Rainfall Panel',
      steps: [
        {
          id: 'rainfall-panel',
          title: 'Rainfall Panel',
          text: "Select a time window — 1, 3, 6, 12, or 24 hours — and the map will update to show how much rain has accumulated in that period. You can also click Rainfall for Tomorrow to see what's expected the next day.",
          target: '[data-tour-id="rainfall-panel-options"]',
          spotlightTargets: [
            '[data-tour-id="rainfall-panel-heading"]',
            '[data-tour-id="rainfall-panel-options"]',
          ],
          placement: 'left',
        },
      ],
    },
  ],
};
